#!/usr/bin/env bash
# Generates AGENTS.md for OpenAI Codex CLI in the target directory.
# Usage: ./adapters/codex.sh [target-dir]
# Default target: current working directory

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TARGET_DIR="${1:-$(pwd)}"
mkdir -p "$TARGET_DIR"
OUT="$TARGET_DIR/AGENTS.md"

# Strip YAML frontmatter from a markdown file
strip_frontmatter() {
  local file="$1"
  awk 'BEGIN{f=0} /^---/{if(f==0){f=1;next}else{f=2;next}} f==2{print}' "$file"
}

# Replace Claude-specific tool instructions with generic equivalents
adapt_tools() {
  sed \
    -e 's/Use `AskUserQuestion`/Ask the user directly/g' \
    -e 's/via `AskUserQuestion`/directly/g' \
    -e 's/use `AskUserQuestion`:/ask:/g' \
    -e 's/`AskUserQuestion`/a direct question to the user/g' \
    -e 's/All questions go through `a direct question to the user`/Always ask the user directly before proceeding/g'
}

echo "Generating AGENTS.md → $OUT"

cat > "$OUT" <<'HEADER'
# Product Design Agent

> This file was generated by product-design-agent-promax for OpenAI Codex CLI.
> Source: https://github.com/micserr/sprout-product-design-agent

You are a senior product designer — opinionated, direct, and collaborative. You push back on weak
briefs, name tradeoffs clearly, and give recommendations rather than lists of options.

**Trigger keywords:** product design, UX, user experience, wireframes, user journey, design review,
usability, design feedback, competitive research, problem framing, HMW statements, JTBD, design brief,
information architecture, prototype, clickable prototype, "make it interactive", "bring it to life",
"run product design", "design agent".

HEADER

# Append agent body (stripped frontmatter, tools adapted)
strip_frontmatter "$SCRIPT_DIR/agents/product-design.md" | adapt_tools >> "$OUT"

echo "" >> "$OUT"
echo "---" >> "$OUT"
echo "" >> "$OUT"
echo "## Skill Reference" >> "$OUT"
echo "" >> "$OUT"
echo "The following skills are available. Apply them when the relevant phase or trigger is active." >> "$OUT"
echo "" >> "$OUT"

SKILLS=(
  "ux-market-research:UX Market Research"
  "problem-framing:Problem Framing"
  "user-journey:User Journey"
  "wireframing:Wireframing"
  "prototype:Prototyping"
  "design-tokens:Design Tokens"
  "design-qa:Design QA"
)

for entry in "${SKILLS[@]}"; do
  slug="${entry%%:*}"
  label="${entry##*:}"
  skill_file="$SCRIPT_DIR/skills/$slug/SKILL.md"
  if [ -f "$skill_file" ]; then
    echo "### $label" >> "$OUT"
    echo "" >> "$OUT"
    strip_frontmatter "$skill_file" | adapt_tools >> "$OUT"
    echo "" >> "$OUT"
    echo "---" >> "$OUT"
    echo "" >> "$OUT"
  fi
done

echo "✓ AGENTS.md generated at $OUT"
